language: cpp
branches:
  only:
  - master
  - dev/travis

matrix:
  include:
    - os: linux
      dist: xenial

before_install:
  - sudo apt-get update
  - sudo apt-get install -y google-mock libgoogle-glog-dev libopencv-imgproc-dev libopencv-highui-dev libopencv-imgcodecs-dev libopencv-core-dev libprotobuf-dev protobuf-compiler libasio-dev libeigen3-dev curl

before_script:
  - mkdir build
  - cd build
  - cmake ..

script: make all check
