language: cpp
branches:
  only:
  - master
notifications:
  email: false

dist: bionic
addons:
  apt:
    packages:
      - libeigen3-dev
      - libboost-system-dev
      - libasio-dev
      - libssl-dev
      - libboost-dev
      - libgoogle-glog-dev
      - libopencv-dev
      - libopencv-imgproc-dev
      - libopencv-highgui-dev
      - libglfw3-dev
      - libglew-dev


before_install:
  - sudo wget https://dl.google.com/go/go1.14.6.linux-amd64.tar.gz
  - sudo tar -C /usr/local -xzf go1.14.6.linux-amd64.tar.gz
  - sudo add-apt-repository -y ppa:maarten-fonville/protobuf
  - sudo apt-get -q update
  - sudo apt-get -y install protobuf-compiler libprotobuf-dev


script:
  - export PATH="/usr/local/go/bin:$PATH"
  - mkdir -p build
  - cd build
  - cmake  -DFORCE_STUB_FRAMEGRABBER_ONLY=On -DEURESYS_FRAMEGRABBER_SUPPORT=Off ..
  - make all check

cache:
  directories:
    - build/_deps
