language: cpp
branches:
  only:
  - master
  - dev/travis

compiler:
  - gcc
  - clang

before_install:
  - sudo apt-get update
  - sudo apt-get install -y googletest libgoogle-glog-dev libopencv-dev librpotobuf-dev protoc libasio-dev libeigen3-dev curl

before_script:
  - mkdir build
  - cd build
  - cmake ..

script: make all check
