name: C++ with CMake CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
env:
  BUILD_TYPE: RelWithDebInfo

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3

    - uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: git-lfs protobuf-compiler libprotobuf-dev libboost-system-dev libopencv-dev libopencv-imgproc-dev libasio-dev libeigen3-dev libglew-dev libglfw3-dev libfontconfig1-dev libfreetype6-dev google-mock libunwind-dev libgoogle-glog-dev
        version: 1.0

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DFORCE_STUB_FRAMEGRABBER_ONLY=On

    - name: Build
      run: make all
      working-directory: ${{github.workspace}}/build

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: make check
